{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "ecommerce-app.fullname" . }}
  namespace: {{ .Values.namespace | default "ecommerce-dev" }}
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "ecommerce-app.fullname" . }}
  port:
    targetPort: http
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  {{- if .Values.route.tls }}
  tls:
    {{- toYaml .Values.route.tls | nindent 4 }}
  {{- end }}
{{- end }}
